org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

minecraft_version=26.1.2
minecraft_version_range=[26.1.2]
neo_version=26.1.2.97

mod_id=njw_librarians_bargain
mod_name=Librarian’s Bargain
mod_license=MIT
mod_version=1.0.0
mod_group_id=net.njw.librariansbargain
